export  const palabras = [
  "casa", "perro", "gato", "libro", "escuela", "sol", "luna", "mar", "rio", "ciudad",
  "arbol", "flor", "puerta", "ventana", "silla", "mesa", "coche", "tren", "avion", "bicicleta",
  "zapato", "camisa", "pantalon", "sombrero", "reloj", "telefono", "computadora", "pantalla", "teclado", "raton",
  "agua", "fuego", "tierra", "aire", "montana", "valle", "bosque", "playa", "arena", "roca",
  "estrella", "planeta", "universo", "cometa", "lago", "nieve", "lluvia", "viento", "tormenta", "nube",
  "pajaro", "pez", "vaca", "cerdo", "oveja", "caballo", "leon", "tigre", "elefante", "mono",
  "musica", "pelicula", "teatro", "dibujo", "pintura", "foto", "video", "historia", "ciencia", "matematica",
  "color", "negro", "blanco", "rojo", "azul", "verde", "amarillo", "morado", "naranja", "rosa",
  "familia", "amigo", "hermano", "hermana", "padre", "madre", "hijo", "hija", "abuelo", "abuela",
  "camino", "puente", "calle", "carretera", "ciudad", "pueblo", "aldea", "mercado", "tienda", "hospital",
  "doctor", "enfermero", "maestro", "estudiante", "niño", "niña", "juego", "deporte", "futbol", "baloncesto","Hippopotamus", "CanisLupus", "FelisCatus", "EquusCaballus", "PantheraLeo",
  "UrsusArctos", "GiraffaCamelopardalis", "Ornithorhynchus", "MacropusRufus",
  "DendrobatesAuratus", "Chloroplast", "Mitochondria", "Photosynthesis",
  "Thermodynamics", "Electrolysis", "Osteology", "Cardiovascular", "Endocrinology",
  "Rhinoceros", "CarcharodonCarcharias", "ElephasMaximus", "BosTaurus", "Lepidoptera",
  "Araneae", "Ctenophora", "Cnidaria", "Platyhelminthes", "Annelida", "Mollusca",
  "Arthropoda", "Echinodermata", "Protozoa", "Bacteriophage", "Streptococcus",
  "Methanobacterium", "Thermoproteus", "Actinobacteria", "Dictyostelium", "XenopusLaevis",
  "AiluropodaMelanoleuca", "SphenodonPunctatus", "CheloniaMydas", "AlligatorMississippiensis",
  "SalmoSalar", "OncorhynchusMykiss", "GadusMorhua", "AnasPlatyrhynchos", "ColumbaLivia",
  "StruthioCamelus", "AraMacao", "PsittacusErithacus", "PantheraTigris", "LynxRufus",
  "CanisFamiliaris", "VulpesVulpes", "OdocoileusVirginianus", "BisonBison", "CapraHircus",
  "OvisAries", "SusScrofa", "CamelusDromedarius", "EquusAsinus", "MustelaPutorius",
  "MartesZibellina", "LemurCatta", "CallithrixJacchus", "MacacaMulatta", "GorillaGorilla",
  "PanTroglodytes", "HomoSapiens", "AptenodytesForsteri", "SpheniscusDemersus",
  "PygoscelisAdelie", "EudyptulaMinor", "PhoenicopterusRuber", "AnserAnser",
  "BrantaCanadensis", "CygnusOlor", "TurdusMerula", "PasserDomesticus",
  "CorvusCorax", "PicaPica", "FringillaCoelebs", "ParusMajor", "TroglodytesTroglodytes",
  "ErithacusRubecula", "SylviaAtricapilla", "DelphinusDelphis", "OrcinusOrca",
  "BalaenopteraMusculus", "MegapteraNovaeangliae", "EubalaenaAustralis",
  "PhyseterMacrocephalus", "TursiopsTruncatus", "CarcharhinusLeucas", "SphyrnaLewini",
  "ChimaeraMonstrosa", "RattusNorvegicus", "MusMusculus", "CaviaPorcellus",
  "OryctolagusCuniculus", "MesocricetusAuratus", "SciurusVulgaris", "TamiasSibiricus",
  "CastorFiber", "ErinaceusEuropaeus", "SorexAraneus", "TalpaEuropaea", "LutraLutra",
  "MustelaErminea", "VulpesLagopus", "AlopexLagopus", "UrsusMaritimus",
  "AiluropodaMelanoleuca", "PantheraOnca", "AcinonyxJubatus", "PumaConcolor",
  "LeopardusPardalis", "FelisSilvestris", "CanisLatrans", "CuonAlpinus",
  "LycaonPictus", "VulpesCanidae", "CervusElaphus", "AlcesAlces", "CapreolusCapreolus",
  "HydrochoerusHydrochaeris", "CaviaAperea", "DolichotisPatagonum", "ChinchillaLanigera",
  "LagostomusMaximus", "OryzomysPalustris", "MyocastorCoypus", "DipodomysMerriami",
  "PeromyscusManiculatus", "MusSpretus", "ApodemusSylvaticus", "RattusRattus",
  "NeotomaFloridana", "TamiasStriatus", "SciurusCarolinensis", "SpermophilusTridecemlineatus",
  "TamanduaTetradactyla", "MyrmecophagaTridactyla", "BradypusVariegatus", "CholoepusHoffmanni",
  "DasypusNovemcinctus", "OrnithorhynchusAnatinus", "TachyglossusAculeatus",
  "Monotremata", "Marsupialia", "Didelphimorphia", "Diprotodontia", "Dasyuromorphia",
  "Peramelemorphia", "Notoryctemorphia", "Microbiota", "Eukaryota", "Prokaryota",
  "Archaeplastida", "Opisthokonta", "Amoebozoa", "Excavata", "Chromalveolata",
  "Rhizaria", "Alveolata", "Stramenopiles", "Haptophyta", "Cryptophyta", "Dinoflagellata",
  "Bacillariophyta", "Chlorophyta", "Charophyta", "Rhodophyta", "Glaucophyta",
  "Pteridophyta", "Gymnospermae", "Angiospermae", "Magnoliopsida", "Liliopsida",
  "Rosopsida", "Asteridae", "Fabaceae", "Poaceae", "Orchidaceae", "Lamiaceae",
  "Solanaceae", "Apiaceae", "Brassicaceae", "Cactaceae", "Euphorbiaceae", "Moraceae",
  "Fagaceae", "Betulaceae", "Pinaceae", "Cupressaceae", "Taxaceae", "Ginkgoaceae",
  "CycasRevoluta", "ZamiaFurfuracea", "EncephalartosTrispinosus", "MacrozamiaMoorei",
  "DioonSpinulosum", "AraucariaAraucana", "AgathisAustralis", "WollemiaNobilis"
];